// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_API_KEY"] ??
        'AIzaSyCZBA6jDzXoQepIvhTWyRYoaXizRuilpQM',
    appId: dotenv.env["FIREBASE_WEB_APP_ID"] ??
        '1:459963001535:web:295ee001cfae88ab8f340a',
    messagingSenderId:
        dotenv.env["FIREBASE_MESSAGING_SENDER_ID"] ?? '459963001535',
    projectId: dotenv.env["FIREBASE_PROJECT_ID"] ?? 'amiad-porat',
    authDomain:
        dotenv.env["FIREBASE_AUTH_DOMAIN"] ?? 'amiad-porat.firebaseapp.com',
    storageBucket:
        dotenv.env["FIREBASE_STORAGE_BUCKET"] ?? 'amiad-porat.appspot.com',
    measurementId: 'G-WGME3337XV',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_API_KEY"] ??
        'AIzaSyCddV76XRuKtdHkEEnBLUQbrwNXd4epQLA',
    appId: dotenv.env["FIREBASE_ANDROID_APP_ID"] ??
        '1:298508107993:android:d9fda3c4fc8359799bbec8',
    messagingSenderId:
        dotenv.env["FIREBASE_MESSAGING_SENDER_ID"] ?? '298508107993',
    projectId: dotenv.env["FIREBASE_PROJECT_ID"] ?? 'amiad-porat-staging',
    storageBucket: dotenv.env["FIREBASE_STORAGE_BUCKET"] ??
        'amiad-porat-staging.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_API_KEY"] ??
        'AIzaSyB-V4f678NofW6LBmB-qU_ig9SBjth5BOM',
    appId: dotenv.env["FIREBASE_IOS_APP_ID"] ??
        '1:459963001535:ios:e2866114ff1251288f340a',
    messagingSenderId:
        dotenv.env["FIREBASE_MESSAGING_SENDER_ID"] ?? '459963001535',
    projectId: dotenv.env["FIREBASE_PROJECT_ID"] ?? 'amiad-porat',
    storageBucket:
        dotenv.env["FIREBASE_STORAGE_BUCKET"] ?? 'amiad-porat.appspot.com',
    iosClientId: dotenv.env["FIREBASE_IOS_CLIENT_ID"] ??
        '459963001535-rhk25bkbofij6ar2dg9q2o7fat1p05a1.apps.googleusercontent.com',
    iosBundleId: 'com.amitinbar.amiadporat',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env["FIREBASE_API_KEY"] ??
        'AIzaSyB-V4f678NofW6LBmB-qU_ig9SBjth5BOM',
    appId: dotenv.env["FIREBASE_IOS_APP_ID"] ??
        '1:459963001535:ios:e2866114ff1251288f340a',
    messagingSenderId:
        dotenv.env["FIREBASE_MESSAGING_SENDER_ID"] ?? '459963001535',
    projectId: dotenv.env["FIREBASE_PROJECT_ID"] ?? 'amiad-porat',
    storageBucket:
        dotenv.env["FIREBASE_STORAGE_BUCKET"] ?? 'amiad-porat.appspot.com',
    iosClientId: dotenv.env["FIREBASE_IOS_CLIENT_ID"] ??
        '459963001535-rhk25bkbofij6ar2dg9q2o7fat1p05a1.apps.googleusercontent.com',
    iosBundleId: 'com.amitinbar.amiadporat',
  );
}
