name: Flutter CI
on:
  push:
    branches:
      - master
jobs:
  build_app_bundle:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
        env:
          KEY_JKS: ${{ secrets.RELEASE_KEYSTORE }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Decode Keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
          gpg -d --passphrase "${{ secrets.RELEASE_PASSPHRASE }}" --batch release.keystore.asc > android/key.jks
      - name: Create key.properties
        run: |
          touch android/key.properties
          echo storePassword=${{ secrets.KEY_PASSWORD }} >> ./android/key.properties
          echo keyPassword=${{ secrets.KEY_PASSWORD }} >> ./android/key.properties
          echo keyAlias=${{ secrets.KEY_ALIAS }} >> ./android/key.properties
          echo storeFile=./key.jks >> ./android/key.properties
      - name: Get dependencies
        run: flutter pub get
      - name: Build appbundle
        run: flutter build appbundle --flavor=production
      - uses: actions/upload-artifact@v1
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/productionRelease/app-production-release.aab
